# Generated by Django 2.2.6 on 2019-11-04 08:24

from django.db import migrations, models
import django.db.models.deletion
import website.meals.forms


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_registrar_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5, validators=[website.meals.forms.validate_zip_code])),
                ('address', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('meal_count', models.IntegerField(validators=[website.meals.forms.validate_meal_count])),
                ('details', models.CharField(max_length=1000)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Registrar')),
            ],
        ),
    ]
