# Generated by Django 2.2.6 on 2019-11-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='meal_count',
            field=models.IntegerField(default=0),
        ),
    ]
