# Generated by Django 2.2.6 on 2019-11-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_registrar_meal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrar',
            name='meal_count',
        ),
        migrations.RemoveField(
            model_name='registrar',
            name='registration_count',
        ),
    ]
